# Helm values for opentelemetry-collector ≥ 0.84.0
# Namespace sugerido: observability
mode: deployment

serviceAccount:
  create: true
  name: otel-collector

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    # Métricas internas del propio Collector (scrape en :8888)
    prometheus/self:
      config:
        scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
              - targets: ['0.0.0.0:8888']

  processors:
    batch: {}

  exporters:
    prometheus:
      endpoint: "0.0.0.0:8889"
      namespace: otel
    # Tempo (traces) – descomenta cuando tengas Tempo
    # tempo:
    #   endpoint: tempo.tempo.svc.cluster.local:4317
    #   tls:
    #     insecure: true

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: []        # añade "tempo" cuando esté listo

# Permite que Prometheus lo descubra automáticamente
serviceMonitor:
  enabled: true
  interval: 15s
  labels:
    release: prometheus      # coincide con label del Prom Operator chart

ports:
  # puerto de scrape para el exporter Prometheus
  prometheus:
    enabled: true
    containerPort: 8889