mode: deployment

serviceAccount:
  create: true
  name: otel-collector

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    prometheus/self:
      config:
        scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
              - targets: ['0.0.0.0:8888']

  processors:
    batch: {}

  exporters:
    prometheus:
      endpoint: "0.0.0.0:8889"
      namespace: otel

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: []        # añade "tempo" cuando esté listo

serviceMonitor:
  enabled: true
  interval: 15s
  labels:
    release: prometheus

ports:
  prometheus:
    enabled: true
    containerPort: 8889