apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd  # Asegúrate de que es el namespace donde está ArgoCD
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.21.0  # Usa la versión que prefieras
    helm:
      releaseName: prometheus
      values: |
        alertmanager:
          enabled: true
        pushgateway:
          enabled: true
          service:
            type: ClusterIP  # Expone el servicio internamente
            port: 9091
          resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 32Mi
          # Configuración adicional del pushgateway
          persistentVolume:
            enabled: false  # Cambia a true si quieres persistencia
        server:
          service:
            type: NodePort  # Cambia a ClusterIP o LoadBalancer si lo necesitas
          # Configurar Prometheus para scrape del pushgateway
          extraScrapeConfigs: |
            - job_name: 'pushgateway'
              static_configs:
                - targets: ['prometheus-pushgateway:9091']
              honor_labels: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring  # Cambia si deseas otro namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true