apiVersion: v1
kind: ConfigMap
metadata:
  name: k8-auth-config
  labels:
    app: k8-auth
data:
  # Payment service configuration
  SPRING_APPLICATION_JSON: |
    {
      "services": {
        "payment": {
          "url": "https://run.mocky.io/v3/a0277545-e653-4f24-8d06-5b00b6cc269c",
          "timeout": 5000,
          "retries": 3
        }
      }
    }