apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/loki
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.47.2
    helm:
      values: |
        loki:
          auth_enabled: false
          server:
            http_listen_port: 3100
            grpc_listen_port: 9095

          storage_config:
            boltdb_shipper:
              active_index_directory: /var/loki/index
              cache_location: /var/loki/index_cache
              shared_store: filesystem
            filesystem:
              directory: /var/loki/chunks

          schema_config:
            configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: index_
                  period: 24h
          limits_config:
            retention_period: 168h                     
            enforce_metric_name: false                
            ingestion_rate_mb: 64                     
            ingestion_burst_size_mb: 128              
            max_streams_per_user: 30000               
            max_line_size: 1048576                    
            max_entries_limit_per_query: 50000        
            max_global_streams_per_user: 15000        
            max_query_parallelism: 32                 
            max_query_series: 10000                   
            max_query_length: 2h                      

          ingester:
            lifecycler:
              ring:
                kvstore:
                  store: inmemory
                replication_factor: 1
              tokens_file_path: /var/loki/tokens
              join_after: 0s
              min_ready_duration: 0s
            chunk_idle_period: 1h
            max_chunk_age: 1h
            chunk_target_size: 1048576
            chunk_retain_period: 30s

          distributor:
            ring:
              kvstore:
                store: inmemory

          compactor:
            working_directory: /var/loki/compactor
            shared_store: filesystem
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150

          chunk_store_config:
            max_look_back_period: 168h

          table_manager:
            retention_deletes_enabled: true
            retention_period: 168h

        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1
          extraArgs:
            - -config.expand-env=true

          persistence:
            enabled: true
            size: 10Gi
            storageClass: local-path

          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi

          extraEnv:
            - name: JAEGER_AGENT_HOST
              value: ""

        read:
          enabled: false
        write:
          enabled: false
        backend:
          enabled: false
        ingester:
          enabled: false
        distributor:
          enabled: false
        querier:
          enabled: false
        queryFrontend:
          enabled: false
        queryScheduler:
          enabled: false
        compactor:
          enabled: false
        ruler:
          enabled: false
        indexGateway:
          enabled: false
        gateway:
          enabled: false
        memcachedExporter:
          enabled: false

        service:
          type: ClusterIP
          port: 3100
          annotations: {}

        serviceMonitor:
          enabled: true
          interval: 30s
          scrapeTimeout: 10s
          labels:
            app: loki
            release: prometheus

        rbac:
          create: true
          pspEnabled: false

        serviceAccount:
          create: true
          name: loki
          annotations: {}

        networkPolicy:
          enabled: false

        global:
          dnsService: "kube-dns"
          dnsNamespace: "kube-system"

        test:
          enabled: false

        tolerations: []
        affinity: {}
        nodeSelector: {}

        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          fsGroup: 10001

        containerSecurityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
    - group: v1
      kind: Service
      jsonPointers:
        - /spec/clusterIP