apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  source:
    repoURL: https://github.com/tu-org/k3s_project.git   # ⇐ tu repo
    targetRevision: main
    path: monitoring/otel-collector                      # ruta al wrapper chart

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true