apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.64.0
    helm:
      releaseName: otel-collector
      values: |
        mode: gateway
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                http:
          exporters:
            prometheus:
              endpoint: "0.0.0.0:9464"
              namespace: k8_auth
          service:
            pipelines:
              metrics:
                receivers: [otlp]
                processors: [batch]
                exporters: [prometheus]
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: []         # añade Tempo cuando lo tengas
        service:
          ports:
            - name: otlp-grpc
              port: 4317
            - name: otlp-http
              port: 4318
            - name: prometheus
              port: 9464