apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd          # donde vive Argo CD
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

  # --- POLÍTICA DE SYNC --------------------------------------------------
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true   # <-- evita la anotación gigante en los CRDs
      - CreateNamespace=true   # crea el ns monitoring si no existe

  # --- ORIGEN ------------------------------------------------------------
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.0.1
    helm:
      releaseName: prom-stack
      # Si algún día aplicas los CRDs a mano, cambia a skipCrds: true
      skipCrds: false
      values: |
        prometheusOperator:
          trimCRDAnnotations: true    # recorta last-applied en los CRDs
          admissionWebhooks:
            patch:
              enabled: false         # <-- elimina el hook que se atascaba

        grafana:
          adminPassword: "changeme"
          service:
            type: NodePort
            nodePort: 32000
            port: 80
            targetPort: 3000

        prometheus:
          prometheusSpec:
            retention: 7d
            serviceMonitorSelectorNilUsesHelmValues: false