grafana:
  adminUser: admin
  adminPassword: prom-operator      # cámbialo o usa Secret
  service:
    type: ClusterIP
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      jvm:
        gnetId: 4701
        revision: 2
        datasource: Prometheus

prometheus:
  serviceMonitor:
    selector:
      matchExpressions:
        - {key: release, operator: Exists}
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false