apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-local-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    chart: nats
    targetRevision: 1.2.2
    helm:
      values: |
        nats:
          replicas: 1
          jetstream:
            enabled: false  # ¡Sin JetStream!
          logging:
            trace: false
            debug: false
        reloader:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: nats-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true