apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - name: pong
        image: hashicorp/http-echo
        args:
        - "-text=pong"
        ports:
        - containerPort: 5678

---

apiVersion: v1
kind: Service
metadata:
  name: pong-service
spec:
  selector:
    app: pong
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  type: NodePort